spring.application.name=ChuanBiThiGK2
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/QLTinTuc?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mypassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true