# Đổi port web
server.port=8081

# Cấu hình kết nối MySQL (Thêm allowPublicKeyRetrieval để chống lỗi kết nối)
spring.datasource.url=jdbc:mysql://localhost:3306/QLTinTuc?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ÉP BUỘC Spring Boot phải hiểu đây là MySQL (Sẽ khắc phục triệt để lỗi Dialect của bạn)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Cấu hình JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true